version: '3.8'

services:
  database:
    image: postgres:13
    container_name: database
    env_file:
      - .env
    ports:
      - '5434:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  places-api:
    build: .
    container_name: places-api
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - .:/usr/src/app

volumes:
  postgres-data:
